<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8kpzwmx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8kpzwmx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8kpzwmx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8kpzwmx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8kpzwmx\appDevDebugProjectContainer([
    'container.build_hash' => '8kpzwmx',
    'container.build_id' => '0b73532b',
    'container.build_time' => 1582469686,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8kpzwmx');
