<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQmurwjt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQmurwjt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQmurwjt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQmurwjt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQmurwjt\appProdProjectContainer([
    'container.build_hash' => 'Qmurwjt',
    'container.build_id' => '3fb0c095',
    'container.build_time' => 1582467665,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQmurwjt');
